apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: pv
    app: db
    db: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql