apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: healthapp.local
    http:
      paths:
      - path: /healthz
        pathType: Exact
        backend:
          service:
            name: healthapp-service
            port:
              number: 80
      - path: /deepz
        pathType: Exact
        backend:
          service:
            name: healthapp-service
            port:
              number: 80
